title: Video-ads
description: Plugin to play ads in b/w movie. Using HTML5, CSS3 and JavaScript Libraries (video.js)
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
